version: '3.8'

services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: emiteai
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/emiteai
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      volumes: ./logs/log
    depends_on:
      - postgres

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
    depends_on:
      - backend
